language: php
dist: xenial

php:
  - 7.1
  - 7.2
  - 7.3

node_js:
  - 10

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules
    - vendor

before_script:
   - travis_retry composer self-update
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest
   - chmod -R o+w vendor/orchestra
   
script:
   - vendor/bin/phpunit --coverage-clover=coverage.xml
  
after_success:
    - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - rm -R public/css
  - rm -R public/js
  - npm install
  - npm run production

deploy:
  target_branch: test_branch_deploy
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
  on:
    branch: master

notifications:
  email:
    recipients:
      - bliz48rus@gmail.com
      - salador2005@yandex.ru
    on_success: never
    on_failure: always
